### ISSUE TITLE
text errors and oddities

### ISSUE THREAD

**Issue by danbjoseph** [AmericanRedCross/OpenMapKitWebsite#11]
in the What is OMK? section, missing a space and the link is not rendering as such:
![screen shot 2015-12-30 at 4 21 42 pm](https://cloud.githubusercontent.com/assets/4806884/12057675/7dfd04e2-af11-11e5-8fff-b20d227b5935.png)

EDIT: related to #12?

**Comment by danbjoseph** [comment]
i don't personally like how the zeros render (like they're sitting higher up). also, will this number be a live, or at least automatically, updated total? if it's not rounded it should rarely end in multiple zeros like that. but instead of worrying about the font i think it might also bother me less if the number be formatted with a comma thousands separator? also, this number is going to be really big... will we use some sort of abbreviation (e.g. 3.4 mil, 285k, etc.)?
![screen shot 2015-12-30 at 4 23 48 pm](https://cloud.githubusercontent.com/assets/4806884/12057712/c0cba418-af11-11e5-8959-895693483a8c.png)

**Comment by danbjoseph** [comment]
will an icon or something go in these green circles?
![screen shot 2015-12-30 at 4 28 52 pm](https://cloud.githubusercontent.com/assets/4806884/12057774/71c1bb04-af12-11e5-8e7d-edbd090b8947.png)

**Comment by danbjoseph** [comment]
i don't like when my screenshots have extraneous notifications visible
![screen shot 2015-12-30 at 4 30 03 pm](https://cloud.githubusercontent.com/assets/4806884/12057820/05369cd8-af13-11e5-8e94-254aa5854e1d.png)

**Comment by danbjoseph** [comment]
font awesome icon on http://americanredcross.github.io/OpenMapKitWebsite/docs.html isn't rendering (others on the same page are)
![screen shot 2015-12-30 at 4 34 56 pm](https://cloud.githubusercontent.com/assets/4806884/12057846/5398b924-af13-11e5-9539-7d7f9cc79fb2.png)
![screen shot 2015-12-30 at 4 35 50 pm](https://cloud.githubusercontent.com/assets/4806884/12057853/6a413598-af13-11e5-81a1-3dde9de2b799.png)

**Comment by danbjoseph** [comment]
on [this page](http://americanredcross.github.io/OpenMapKitWebsite/docs_createomksurvey.html)
> An OSM question is a new 'media type', which means that it functions in the survey in the same manor as a photo or video.

manner not manor

**Comment by mojodna** [comment]
> manner not manor

You sure? It might only work on the same estate where the photo was taken.

**Comment by danbjoseph** [comment]
:+1:

**Comment by jharpster** [comment]
Fixed the random mis-spelling and formatting errors. Cut the whole quick stats section since there is currently no way to populate with reasonable looking numbers.
