### ISSUE TITLE
github pages build error for custom markdown plugin

### ISSUE THREAD

**Issue by danielduhh** [AmericanRedCross/OpenMapKitWebsite#12]
Page fails to build custom markdown liquid tag. Looks like github doesn't allow custom jekyll plugins (https://github.com/jekyll/jekyll/issues/325). Need to make sure this isn't the case when hosting the site on openmapkit.org

**Comment by hallahan** [comment]
You can push only the build files to gh-pages branch, building the site on your dev box instead of behind the scenes at Github. That should do the trick.

**Comment by mojodna** [comment]
Consider using Travis to build + deploy (using https://github.com/X1011/git-directory-deploy). This is how we deploy the City Energy Project sites.

See https://github.com/cityenergyproject/saltlakecity/blob/master/.travis.yml and https://github.com/cityenergyproject/saltlakecity/blob/master/deploy.sh for reference.

The secure string is the output of `travis encrypt GIT_DEPLOY_REPO=https://<token>@github.com/<repo>`.

**Comment by hallahan** [comment]
:+1:

**Comment by danielduhh** [comment]
Hosting site on new ec2, link is in the #general slack channel
