### ISSUE TITLE
format documentation for easier reading

### ISSUE THREAD

**Issue by danbjoseph** [AmericanRedCross/OpenMapKitWebsite#13]
right now there is minimal formatting on this site (when looking at http://americanredcross.github.io/OpenMapKitWebsite/docs_createomksurvey.html)

xlsform.org does a good job of using bold formatting and tables to help visually guide the reader

Boundless starts their [tutorials](http://workshops.boundlessgeo.com/postgis-intro/welcome.html) with a nice welcome that describes the typographic conventions they use:
>These sections conform to a number of conventions to make it easier to follow the conversation. This section gives a brief overview of what to expect in the way of typographic conventions, as well as a short overview of the structure of each workbook.

**Comment by jharpster** [comment]
We're implementing style sheets to help the formatting of the markdown. l
