### ISSUE TITLE
sidebar 'shuffle and hop' when scrolling

### ISSUE THREAD

**Issue by danbjoseph** [AmericanRedCross/OpenMapKitWebsite#14]
when scrolling down the sidebar menu adjusts the text spacing and then hops further left. this doesn't seem to be doing something helpful in terms of responsiveness and is visually distracting.

![screen shot 2015-12-30 at 4 49 05 pm](https://cloud.githubusercontent.com/assets/4806884/12058028/7d5b394c-af15-11e5-93e8-2dc46ab096ef.png)
![screen shot 2015-12-30 at 4 49 13 pm](https://cloud.githubusercontent.com/assets/4806884/12058029/7e6c0abe-af15-11e5-96df-b2829098a8d9.png)
![screen shot 2015-12-30 at 4 49 18 pm](https://cloud.githubusercontent.com/assets/4806884/12058030/7ff20b86-af15-11e5-92e2-bb218914d013.png)

**Comment by danielduhh** [comment]
we're using a new sticky sidebar on the docs page
![screen shot 2016-01-08 at 9 17 03 am](https://cloud.githubusercontent.com/assets/1947857/12204356/a6f1bd88-b5e8-11e5-842e-2acacf3fbc9a.png)
