### ISSUE TITLE
site still isn't working

### ISSUE THREAD

**Issue by dalekunce** [AmericanRedCross/OpenMapKitWebsite#5]
We can we expect to see the site turned on?

**Comment by hallahan** [comment]
@jharpster or @danielduhh - Could you please look into this? Godaddy DNS server's CNAME is pointing to the wrong place after the repo moved. You need a push this Jekyll site to the `gh-pages` branch. There needs to be a CNAME file in the root of the repo as well.

https://help.github.com/articles/setting-up-a-custom-domain-with-github-pages/

**Comment by hallahan** [comment]
For now, you can peek at what's there here:

http://americanredcross.github.io/OpenMapKitWebsite/

**Comment by jharpster** [comment]
Done and Done.

**Comment by jharpster** [comment]
@naomi Wasn't quite ready. When we're done with the docs, will redirect the cname again

**Comment by danielduhh** [comment]
Link to dev site is posted in #general slack channel
